name: release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            name: windows-amd64
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
            name: linux-amd64
          - target: x86_64-apple-darwin
            archive: tar.gz tar.xz
            name: darwin-amd64
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          ARCHIVE_NAME: git_user_manager-${{ github.event.release.tag_name }}-${{ matrix.name }}

  cargo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: --allow-dirty

  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    needs: release
    steps:
      - name: Release to Homebrew tap
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: Sarrus1
          homebrew_tap: homebrew-formulas
          formula_folder: formula
          github_token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          commit_owner: Sarrus1
          commit_email: 63302440+Sarrus1@users.noreply.github.com
          install: 'bin.install "gum" => "gum"'
          target_darwin_amd64: true
          target_darwin_arm64: false
          target_linux_amd64: true
          target_linux_arm64: false
          update_readme_table: true
          skip_commit: false
          debug: true
